mqtt:
  broker:
    host: "broker.hivemq.com"
    port: 1883
    websocket_port: 8000
    keepalive: 60
    
  topics:
    status: "climbing/+/status"
    telemetry: "climbing/+/telemetry"
    telegram_response: "climbing/+/telegram"
    device_request: "climbing/{serial}/request"
    
  qos:
    subscribe: 1
    publish: 1
    
  client:
    id_prefix: "climbing_companion_"
    clean_session: true
    reconnect_delay: 5
    max_reconnect_attempts: 10
