schemas:
  common_fields:
    profile:
      created_at: datetime
      
    metadata:
      created_at: datetime

  entity:
    data:
      session_id: str
      device_serial: str
      trace: List[Dict]

  validations:
    mandatory_fields:
      profile:
        - created_at
      data:
        - session_id
        - device_serial
        - trace

    type_constraints:
      trace:
        item_constraints:
          required_fields:
            - height
            - time
          type_mappings:
            height: float
            time: int
