schemas:
  common_fields:
    profile:
      create_at: datetime
      
    metadata:
      created_at: datetime

  entity:
    data:
      session_id: str
      device_serial: str
      alt: float

  validations:
    mandatory_fields:
      profile:
        - create_at
      data:
        - session_id
        - device_serial
        - alt
